little-asp-net-core-book/AspNetCoreTodo/Models/ErrorViewModel.cs
namespace AspNetCoreTodo.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

little-asp-net-core-book/AspNetCoreTodo/Models/TodoItem.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreTodo.Models
{
    public class TodoItem
    {
        public Guid Id { get; set; }

        public bool IsDone { get; set; }

        [Required]
        public string Title { get; set; }

        public DateTimeOffset? DueAt { get; set; }
    }
}

little-asp-net-core-book/AspNetCoreTodo/Models/TodoViewModel.cs
namespace AspNetCoreTodo.Models
{
    public class TodoViewModel
    {
        public TodoItem[] Items { get; set; }
    }
}

little-asp-net-core-book/AspNetCoreTodo/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspNetCoreTodo.Models;

namespace AspNetCoreTodo.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

little-asp-net-core-book/AspNetCoreTodo/Controllers/TodoController.cs
using Microsoft.AspNetCore.Mvc;
using AspNetCoreTodo.Services;
using AspNetCoreTodo.Models;

namespace AspNetCoreTodo.Controllers
{
    public class TodoController : Controller
    {
		private readonly ITodoItemService _todoItemService;

		public TodoController(ITodoItemService todoItemService)
		{
			_todoItemService = todoItemService;
		}

		public async Task<IActionResult> index()
		{
			var items = await _todoItemService.GetIncompleteItemsAsync();

			var model = new TodoViewModel()
			{
				Items = items
			};

			return View(model);
		}

		[ValidateAntiForgeryToken]
		public async Task<IActionResult> AddItem(TodoItem newItem)
		{
			if (!ModelState.IsValid)
			{
				return RedirectToAction("Index");
			}

			var successful = await _todoItemService.AddItemAsync(newItem);
			if (!successful)
			{
				return BadRequest("Could not add item.");
			}

			return RedirectToAction("Index");
		}

		[ValidateAntiForgeryToken]
		public async Task<IActionResult> MarkDone(Guid id)
		{
			if (id == Guid.Empty)
			{
				return RedirectToAction("Index");
			}

			var successful = await _todoItemService.MarkDoneAsync(id);
			if (!successful)
			{
				return BadRequest("Could not mark item as done.");
			}

			return RedirectToAction("Index");
		}
    }
}

little-asp-net-core-book/AspNetCoreTodo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

little-asp-net-core-book/AspNetCoreTodo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCoreTodo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspNetCoreTodo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNetCoreTodo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
							<a class="nav-link text-dark" asp-area=""  asp-controller="Todo" asp-action="Index">My to-dos</a>
						</li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AspNetCoreTodo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

little-asp-net-core-book/AspNetCoreTodo/Views/Todo/AddItemPartial.cshtml
@model TodoItem

<form asp-action="AddItem" method="POST">
    <label asp-for="Title">Add a new item:</label>
    <input asp-for="Title">
    <button type="submit">Add</button>
</form>

little-asp-net-core-book/AspNetCoreTodo/Views/Todo/Index.cshtml
@model TodoViewModel
@using Humanizer

@{
	ViewData["Title"] = "Manage your todo list";
}
<div class="panel panel-default todo-panel">
	<div class="panel-heading">@ViewData["Title"]</div>
		<table class="table table-hover">
			<thead>
			<tr>
			<td>&#x2714;</td>
			<td>Item</td>
			<td>Due</td>
			</tr>
			</thead>
			@foreach (var item in Model.Items)
			{
				<tr>
					<td>
						<form asp-action="MarkDone" method="POST">
							<input type="checkbox" class="done-checkbox">
							<input type="hidden" name="id" value="@item.Id">
						</form>
					</td>
					<td>@item.Title</td>
					<td>@item.DueAt.Humanize()</td>
				</tr>
			}
		</table>
	<div class="panel-footer add-item-form">
	  @await Html.PartialAsync("AddItemPartial", new TodoItem())
	</div>
</div>